name: Pull Request Lookaside Management

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      url-slug: ${{ steps.url-slug.outputs.URL_SLUG }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Node dependencies
        run: npm install

      - name: Create URL slug
        id: url-slug
        run: |
          echo "URL_SLUG=${{ github.event.repository.name }}/${{
            github.event.pull_request.head.ref }}-${{
            github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Build website with Eleventy
        run:
          npm run build -- --pathprefix=/lookasides/${{
          steps.url-slug.outputs.URL_SLUG }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  deploy:
    needs: build
    environment:
      name: lookaside
      url:
        https://neillrobson.com/lookasides/${{ needs.build.outputs.url-slug }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lookaside repo
        uses: actions/checkout@v4
        with:
          repository: neillrobson/lookasides
          token: ${{ secrets.LOOKASIDE_PAT }}

      - name: Clear directory
        run: rm -rf "${{ needs.build.outputs.url-slug }}"

      - name: Create directory
        run: mkdir -p "${{ needs.build.outputs.url-slug }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ${{ needs.build.outputs.url-slug }}

      - name: Commit and push
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions Bot"
          git add .
          git commit -m "Update lookaside for ${{ needs.build.outputs.url-slug }}"
          git push origin main
